Repository UBC-MDS/salesanalyzer, pull requests merged in 2025-01, with the labels that each got.

#9 predict fxn docs + README.md updates
  README.md
  src/salesanalyzer/salesanalyzer.py
Labels: documentation

#11 Market segmentation Function
  CODE_OF_CONDUCT.md
  README.md
  src/salesanalyzer/salesanalyzer.py
Labels: documentation, enhancement

#12 changes to readme
  CONDUCT.md
  README.md
Labels: documentation

#18 changed pyhton version
  pyproject.toml
Labels: enhancement

#19 Predictfxn
  =3.12
  poetry.lock
  pyproject.toml
  src/salesanalyzer/predict_sales.py
  tests/test_data.csv
  tests/test_predictSales.py
  tests/test_predict_sales.py
Labels: enhancement

#20 Tests for summary statistics
  src/salesanalyzer/sales_summary_statistics.py
  tests/test_sales_summary_statistics.py
Labels: enhancement

#27 Predictfxn
  =3.12
  src/salesanalyzer/predict_sales.py
  tests/test_predict_sales.py
Labels: enhancement

#39 added predict fxn to examples
  docs/example.ipynb
Labels: documentation

#40 Closes #35: Docs segment revenue share
  docs/example.ipynb
  src/salesanalyzer/segment_revenue_share.py
Labels: documentation

#43 updated sample data in example.ipynb
  docs/example.ipynb
Labels: documentation

#44 documentataion updates for sphynx
  README.md
  docs/example.ipynb
  src/salesanalyzer/predict_sales.py
  src/salesanalyzer/sales_summary_statistics.py
Labels: documentation

#45 docs: Removed Country column from sample_data
  docs/example.ipynb
  poetry.lock
  pyproject.toml
  src/salesanalyzer/sales_summary_statistics.py
  src/salesanalyzer/segment_revenue_share.py
  tests/test_predict_sales.py
  tests/test_sales_summary_statistics.py
  tests/test_segment_revenue_share.py
Labels: documentation

#53 fix: modified package name to salesanalyzer-mds
  .github/workflows/ci-cd.yml
  CHANGELOG.md
  docs/conf.py
  docs/example.ipynb
  pyproject.toml
  src/salesanalyzer_mds/__init__.py
  src/salesanalyzer_mds/predict_sales.py
  src/salesanalyzer_mds/sales_summary_statistics.py
  src/salesanalyzer_mds/segment_revenue_share.py
  tests/test_predict_sales.py
  tests/test_sales_summary_statistics.py
  tests/test_segment_revenue_share.py
Labels: enhancement
